import "./globals.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const khula = localFont({
  src: [
    {
      path: "./fonts/Khula/Khula-Bold.woff",
      weight: "700",
      style: "normal",
      variable: "--font-Khula",
      display: "swap",
    },
    {
      path: "./fonts/Khula/Khula-SemiBold.woff",
      weight: "600",
      style: "normal",
      variable: "--font-Khula",
      display: "swap",
    },
    {
      path: "./fonts/Khula/Khula-Regular.woff",
      weight: "400",
      style: "normal",
      variable: "--font-Khula",
      display: "swap",
    },
    {
      path: "./fonts/Khula/Khula-Light.woff",
      weight: "300",
      style: "normal",
      variable: "--font-Khula",
      display: "swap",
    },
  ],
});

const nunito = localFont({
  src: [
    {
      path: "./fonts/Nunito/static/Nunito-Medium.ttf",
      weight: "500",
      style: "normal",
      variable: "--font-Nunito",
      display: "swap",
    },
    {
      path: "./fonts/Nunito/static/Nunito-Bold.ttf",
      weight: "700",
      style: "normal",
      variable: "--font-Nunito",
      display: "swap",
    },
  ],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${khula.className}${nunito.className}`}>{children}</body>
    </html>
  );
}
